application: pyascii
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /stylesheet\.css
  static_files: stylesheet.css
  upload: stylesheet\.css

- url: /client\.js
  static_files: client.js
  upload: client\.js


- url: /
  static_files: index.html
  upload: index\.html

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: numpy
  version: "latest"
